---
apiVersion: v1
kind: ConfigMap
metadata:
  name: syncflaer
data:
  config.yml: |
    ---
    notifications:
      slack:
        webhookURL: env:SLACK_WEBHOOK_URL
    traefikInstances:
      - name: main
        url: https://traefik.example.com
        ignoredRules:
          - local.example.com
          - dev.example.com

    additionalRecords:
      - name: vpn.example.com
        ttl: 120
        proxied: false

    cloudflare:
      apiToken: env:CF_API_TOKEN
      zoneNames:
        - example.com
      deleteGrace: 5
      defaults:
        type: CNAME
        proxied: true
        ttl: 1
