---
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: syncflaer
  namespace: syncflaer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-all-ingresses
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syncflaer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-all-ingresses
subjects:
  - kind: ServiceAccount
    name: syncflaer
    namespace: syncflaer
