---
# a list of services that return the public IP
ipProviders:
  - https://ifconfig.me/ip
  - https://ipecho.net/plain
  - https://myip.is/ip

# configure Slack notifications for SyncFlaer
notifications:
  slack:
    # Slack webhook URL
    webhookURL: https://hooks.slack.com/services/abc/def  # can also be set using an env variable (e.g. env:SLACK_TOKEN)
    username: SyncFlaer
    channel: "#syncflaer"
    iconURL: https://url.to/image.png

traefikInstances:
    # the name of the Traefik instance
  - name: main
    # base URL for Traefik dashboard and API (https://doc.traefik.io/traefik/operations/api/)
    url: https://traefik.example.com
    # HTTP basic auth credentials for Traefik
    username: admin
    password: supersecure  # can also be set using an env variable by setting the value to 'env:ENV_VAR_NAME' (e.g. env:TRAEFIK_FIRST_PW)
    # you can set http headers that will be added to the Traefik api request
    # requires string keys and string values
    customRequestHeaders:
      # headers can either be key value pairs in plain text
      X-Example-Header: Example-Value
      # or the value can be imported from env variables using the 'env:' prefix
      Authorization: env:MY_AUTH_VAR  # in this case $MY_AUTH_VAR env variable will be used as the value
    # a list of rules which will be ignored
    # these rules are matched as a substring of the entire Traefik rule (i.e test.local.example.com would also match)
    ignoredRules:
      - local.example.com
      - dev.example.com
    # you can add a second instance
  - name: secondary
    url: https://traefik-secondary.example.com
    username: admin
    password: stillsupersecure  # can also be set using an env variable by setting the value to 'env:ENV_VAR_NAME' (e.g. env:TRAEFIK_TWO_PW)
    ignoredRules:
      - example.example.com
      - internal.example.com

# specify additional DNS records for services absent in Traefik (i.e. vpn server)
additionalRecords:
  - name: vpn.example.com
    ttl: 120
    proxied: false
  - name: a.example.com
    proxied: true
    type: A
    contents: 1.1.1.1

cloudflare:
  # global Cloudflare API token
  apiToken: abc  # can also be set using an env variable (e.g. env:CF_API_TOKEN)
  # a list of Cloudflare zone names
  zoneNames:
    - example.com
    - othersite.com
  # define how many skips should happen until a DNS record gets deleted
  # every run of SyncFlaer counts as a skip
  deleteGrace: 5
  # define a set of defaults applied to all Traefik rules
  defaults:
    type: CNAME
    proxied: true
    ttl: 1
