---
# a list of services that return the public IP
ipProviders:
  - https://ifconfig.me/ip
  - https://ipecho.net/plain
  - https://myip.is/ip

# configure Slack notifications for SyncFlaer
notifications:
  slack:
    # Slack webhook URL
    # you can set the value directly in config file
    webhookURL: https://hooks.slack.com/services/abc/def
    # or by using an environment variable by using the 'env:' prefix
    # webhookURL: env:SLACK_WEBHOOK_URL  # in this case the contents of $SLACK_WEBHOOK_URL environment variable will be used as the value
    username: SyncFlaer
    channel: "#syncflaer"
    iconURL: https://url.to/image.png

traefikInstances:
    # the name of the Traefik instance
  - name: main
    # base URL for Traefik dashboard and API (https://doc.traefik.io/traefik/operations/api/)
    url: https://traefik.example.com
    # HTTP basic auth credentials for Traefik
    username: admin
    # you can set the value directly in config file
    password: supersecure
    # or by using an environment variable using the 'env:' prefix
    # password: env:TRAEFIK_PW  # in this case the contents of $TRAEFIK_PW environment variable will be used as the value
    # you can set http headers that will be added to the Traefik api request
    # requires string keys and string values
    customRequestHeaders:
      # headers can either be key value pairs in plain text
      X-Example-Header: Example-Value
      # or the value can be imported from environment variables using the 'env:' prefix
      Authorization: env:MY_AUTH_VAR  # in this case the contents of $MY_AUTH_VAR environment variable will be used as the value
    # a list of rules which will be ignored
    # these rules are matched as a substring of the entire Traefik rule (i.e test.local.example.com would also match)
    ignoredRules:
      - local.example.com
      - dev.example.com
    # you can define overrides for the default settings for each Traefik rule
    # this can be useful, if you want to have some rules with different settings than the ones defined in cloudflare.defaults
    defaultOverrides:
        # host must match with the host of the Traefik rule
      - rule: my.example.com
        # specify the overrides (type, content, proxied, ttl)
        proxied: false
        ttl: 120
      - rule: other.example.com
        type: A
        content: 1.1.1.1
        proxied: false
        ttl: 300
  # you can add a second instance
  - name: secondary
    url: https://traefik-secondary.example.com
    username: admin
    password: stillsupersecure
    ignoredRules:
      - example.example.com
      - internal.example.com

# enable kubernetes ingress integration
kubernetes:
  enabled: true

# set whether you want to have the root record managed by SyncFlaer
# if you don't need a root record, you can set this to false
# it is also helpful to set this to false if your root record points to a different server
managedRootRecord: true

# specify additional DNS records for services absent in Traefik (i.e. vpn server)
additionalRecords:
  - name: vpn.example.com
    ttl: 120
    proxied: false
  - name: a.example.com
    proxied: true
    type: A
    contents: 1.1.1.1

cloudflare:
  # global Cloudflare API token
  # you can set the value directly in config file
  apiToken: abc
  # or by using an environment variable using the 'env:' prefix
  # apiToken: env:CF_API_TOKEN  # in this case the contents of $CF_API_TOKEN environment variable will be used as the value
  # a list of Cloudflare zone names
  zoneNames:
    - example.com
    - othersite.com
  # define how many skips should happen until a DNS record gets deleted
  # every run of SyncFlaer counts as a skip
  deleteGrace: 5
  # define a set of defaults applied to all DNS records
  # they can be overridden by either specifying them in traefikInstances.defaultOverrides or by using Kubernetes Ingress annotations
  # check the README for more information
  defaults:
    type: CNAME
    proxied: true
    ttl: 1
