---
name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout=3m
